ApiStatus.create(name: "twelio", url: "https://example-api-tray.herokuapp.com/api/v1/twilios", has_sunset: false, is_deprecated: false, sunset_date: nil )
ApiStatus.create(name: "aircalls", url: "https://example-api-tray.herokuapp.com/api/v2/aircalls", has_sunset: false, is_deprecated: false, sunset_date: nil )
ApiStatus.create(name: "asanas", url: "https://example-api-tray.herokuapp.com/api/v3/asanas", has_sunset: false, is_deprecated: false, sunset_date: nil )
ApiStatus.create(name: "kissflows", url: "https://example-api-tray.herokuapp.com/api/v4/kissflows", has_sunset: false, is_deprecated: false, sunset_date: nil )
ApiStatus.create(name: "gustos", url: "https://example-api-tray.herokuapp.com/api/v5/gustos", has_sunset: false, is_deprecated: false, sunset_date: nil )
ApiStatus.create(name: "gitlabs", url: "https://example-api-tray.herokuapp.com/api/v6/gitlabs", has_sunset: false, is_deprecated: false, sunset_date: nil )
ApiStatus.create(name: "rydoos", url: "https://example-api-tray.herokuapp.com/api/v7/rydoos", has_sunset: false, is_deprecated: false, sunset_date: nil )
ApiStatus.create(name: "stripes", url: "https://example-api-tray.herokuapp.com/api/v8/stripes", has_sunset: false, is_deprecated: false, sunset_date: nil )
ApiStatus.create(name: "postmans", url: "https://example-api-tray.herokuapp.com/api/v9/postmans", has_sunset: false, is_deprecated: false, sunset_date: nil )
# ApiStatus.create(name: "casavis", url: "https://example-api-tray.herokuapp.com/api/v10/casavi", has_sunset: false, is_deprecated: false, sunset_date: nil )